title: BioMedICUS
description: A system for large-scale text analysis and processing of biomedical and clinical reports
theme: just-the-docs/just-the-docs

url: https://nlpie.github.io/biomedicus

aux_links:
  GitHub: https://github.com/nlpie/biomedicus

nav_external_links:
  - title: BioMedICUS GitHub
    url: https://github.com/nlpie/biomedicus
  - title: MTAP Documentation
    url: https://nlpie.github.io/mtap
  - title: NLP-IE Group
    url: https://nlpie.github.io/


callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
