global:
  host: null
  mtapConfig: null
  logLevel: INFO
  register: no
eventsService:
  enabled: no
  port: 50100
  workers: 8
sharedProcessorConfig:
  eventsAddress: 127.0.0.1:50100
  workers: 8
  args: [ ]
  jvmArgs: [ "-Xms32m", "-Xmx8g" ]
  javaClasspath: null
# Below this is a list of the processors to be deployed and their individual settings.
processors:
  - implementation: java
    enabled: no
    entryPoint: edu.umn.biomedicus.rtf.RtfProcessor
    port: 50200
  - implementation: python
    entryPoint: biomedicus.sentences.bi_lstm
    port: 50300
    preArgs: ['processor']
  - implementation: java
    entryPoint: edu.umn.biomedicus.tagging.tnt.TntPosTaggerProcessor
    port: 50400
  - implementation: java
    entryPoint: edu.umn.biomedicus.acronym.AcronymDetectorProcessor
    port: 50500
  - implementation: java
    entryPoint: edu.umn.biomedicus.concepts.DictionaryConceptDetector
    port: 50600
  - implementation: python
    entryPoint: biomedicus.negation.negex_triggers
    port: 50700
  - implementation: python
    entryPoint: biomedicus.dependencies.stanza_selective_parser
    port: 50800
    startupTimeout: 180
  - implementation: python
    entryPoint: biomedicus.negation.deepen
    port: 50900
  - implementation: java
    entryPoint: edu.umn.biomedicus.sections.RuleBasedSectionHeaderDetector
    port: 51000
