FROM mtap:latest

ARG DEBIAN_FRONTEND=noninteractive

WORKDIR /home/biomedicus3

COPY . biomedicus3

RUN pip3 install ./biomedicus3
RUN biomedicus download-data --with-stanza

COPY ./python/biomedicus/deployment/biomedicus_deploy_config.yml .
COPY ./python/biomedicus/pipeline/biomedicus_default_pipeline.yml .
COPY ./tools/docker/biomedicus.sh .

RUN chmod +x biomedicus.sh

EXPOSE 50100/tcp
EXPOSE 50200/tcp
EXPOSE 50300/tcp
EXPOSE 50400/tcp
EXPOSE 50500/tcp
EXPOSE 50600/tcp
EXPOSE 50700/tcp
EXPOSE 50800/tcp
EXPOSE 50900/tcp
EXPOSE 51000/tcp

ENTRYPOINT ./biomedicus.sh
