# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '3.0.0rc6.dev1+g2bfbe6b.d20230112'
__version_tuple__ = version_tuple = (3, 0, 0, 'dev1', 'g2bfbe6b.d20230112')
