name: Deploy Jekyll site to Pages

on:
  workflow_dispatch:
  
jobs:
  nothing:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Fail
        id: fail
        run: |
          exit 1
