# This file exists so the pages build can be triggered on the gh-pages branch.
# On this branch and all other branches it does nothing.

name: Deploy Jekyll site to Pages

on:
  workflow_dispatch:
  
jobs:
  nothing:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Fail
        id: fail
        run: |
          exit 1
