# paths can be set here, by environment variable or java property.
paths:
  #home: /absolute-path
  #data: /absolute-path
# settings ending in path will be loaded as Path, if not absolute they will be resolved against the data directory
settings:
  vocabulary:
    wordIndex.path: vocabulary/words.txt
    specialist.words.path: vocabulary/specialist-words.txt
  spelling:
    arpa.path: spell/UPMC.arpa
    maxEditDistance: 4
  tnt:
    trigram.path: tnt/trigram.yml
    word.path: tnt/words/
    beam.threshold: 2.0
  normalization:
    lexicon.path: normalization/lexicon.yml
    fallback.path: normalization/fallbackLexicon.yml
  acronym:
    useAlignment: false
    expansionsModel.path: acronym/expansions.txt
    alignmentModel.path: acronym/alignment.yml
    model: vector
    vector:
      model.path: acronym/vectorSpace.yml
      trainer:
        expansionMap.path: /path-to
        uniqueIdMap.path: /path-to
        longforms.path: /path-to
        outputDir.path: /path-to
    senseMap.path: acronym/senseMap.ser
    acronymExpansions.path: acronym/acronymExpansions.yml
    orthographicModel.path: acronym/orthographicModel.yml
  semanticNetwork:
    srdef.path: semnetwork/SRDEF
    semgroups.path: semnetwork/SemGroups.txt
  concepts:
    phrases.path: concepts/phrases.txt
    norms.path: concepts/norms.txt
    filters:
      sui.path: conceptFilters/filteredSuis.txt
      suicui.path: conceptFilters/filteredSuiCuis.txt
      cui.path: conceptFilters/filteredCuis.txt
      tui.path: conceptFilters/filteredTuis.txt
  sections.headers.path: sections/headers.txt
  parser.implementation: opennlp
  opennlp:
    parser.model.path: opennlp/en-parser-chunking.bin
    sentence.model.path: NOT_USED
  specialist.path: SPECIALIST/LEX
  socialhistory:
    parser: opennlp
# these indicate settings keys which are bound against a certain class
settingInterfaces:
  parser.implementation: edu.umn.biomedicus.parsing.Parser
  acronym.model: edu.umn.biomedicus.acronym.AcronymModel
  socialhistory.parser: edu.umn.biomedicus.parsing.Parser
# these indicate the options for the bindings above
interfaceImplementations:
  edu.umn.biomedicus.parsing.Parser:
    opennlp: edu.umn.biomedicus.opennlp.OpenNlpParser
  edu.umn.biomedicus.acronym.AcronymModel:
    vector: edu.umn.biomedicus.acronym.AcronymVectorModel
